In [2]:
import numpy as np

HOW TO CREATE AN ARRAY


In [3]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [4]:
type(a)

numpy.ndarray

Basic Operations of Array


In [5]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [6]:
# Creating a 2d array
a2 = np.array([[1,2,3],[4,5,6]])#ek array ke andar hmne do sub array diye hue hai ise 2d banane ke liye 
print(a2)

[[1 2 3]
 [4 5 6]]


In [7]:
# Creating a 3d array
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


for finding a shape of array we use .shape

In [8]:
print(a2.shape)#2d ke andar 2 rows and 3 columns hai 
print(a3.shape)#2 2d arrays with 2 rows and 3 columns

(2, 3)
(2, 2, 3)


for finding a dimension we use .ndim


In [9]:
print(a2.ndim) #number of dimension find karte hai 
print(a3.ndim)

2
3


.dtype is used to find a innerdatype of array

In [10]:
print(a2.dtype) #array ke andar ke element ke dataype ko batata hai .dtype 

int64


numpy me range dene ke liye ham .arange ka use karte hai 

In [11]:
np.arange(11) #arange method ke through hame 1d array mil jata hai 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
np.random.randint(1,11, size =(3,3)) #2d array 

array([[5, 5, 8],
       [4, 6, 3],
       [3, 2, 3]], dtype=int32)

In [15]:
x = np.array([[7,2,3],
             [2,5,2],
             [3,5,1]]) #2d array with 3 rows and 3 coloumn
y = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])# 2d array with 3 rows and 3 coloumn
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(x+y)
print(x-y)
print(x*y)

[[ 8  4  6]
 [ 6 10  8]
 [10 13 10]]
[[ 6  0  0]
 [-2  0 -4]
 [-4 -3 -8]]
[[ 7  4  9]
 [ 8 25 12]
 [21 40  9]]


In [17]:
print(x@y) #matrix multiplication 

[[36 48 60]
 [36 45 54]
 [30 39 48]]


In [18]:
np.dot(x,y) #dot method is used for mtrix multiplication 

array([[36, 48, 60],
       [36, 45, 54],
       [30, 39, 48]])

In [19]:
np.prod(x) #prod method is used for multiply the all element of matrix and give total product of the element 

np.int64(12600)

In [20]:
x.prod() #product of all element in the array

np.int64(12600)

In [21]:
x.mean() # mean of all elements in the array

np.float64(3.3333333333333335)

In [22]:
y.mean()

np.float64(5.0)

In [23]:
x.mean(axis=0)#find the mean of each coloum when we set axis at 0

array([4., 4., 2.])

In [24]:
y.mean(axis=1)#find the mean of each row when we set axis at 1

array([2., 5., 8.])

In [25]:
print(x.sum())#sum of all element in the array
print(x.var())# variance of all elements in the array
print(x.std())# standard deviation of all elements in the array

30
3.3333333333333335
1.8257418583505538


In [26]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a, 25)) #25th percentile
print(np.percentile(a, 50)) #50th percentile 
print(np.percentile(a, 75)) #75th percentile

3.0
5.0
7.0


In [27]:
b = np.array([[59,29,93,93],
              [84,60,30,66],
              [66,63,38,20],
              [31,32,61,92]])
print(b)

[[59 29 93 93]
 [84 60 30 66]
 [66 63 38 20]
 [31 32 61 92]]


In [28]:
print('2x8')
print(b.reshape(2,8))

2x8
[[59 29 93 93 84 60 30 66]
 [66 63 38 20 31 32 61 92]]


In [29]:
print('8x2')
print(b.reshape(8,2))

8x2
[[59 29]
 [93 93]
 [84 60]
 [30 66]
 [66 63]
 [38 20]
 [31 32]
 [61 92]]


In [30]:
print(b)

[[59 29 93 93]
 [84 60 30 66]
 [66 63 38 20]
 [31 32 61 92]]


- indexing in numpy

In [31]:
print(b[0])
print(b[1])

[59 29 93 93]
[84 60 30 66]


In [32]:
print(b[0,1])

29


In [33]:
print(b[0,0])

59


- slicing in numpy

In [34]:
print(b[:3])

[[59 29 93 93]
 [84 60 30 66]
 [66 63 38 20]]


In [35]:
print(b[3:])

[[31 32 61 92]]
