In [2]:
import numpy as np

HOW TO CREATE AN ARRAY


In [4]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [5]:
type(a)

numpy.ndarray

Basic Operations of Array


In [7]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [8]:
# Creating a 2d array
a2 = np.array([[1,2,3],[4,5,6]])#ek array ke andar hmne do sub array diye hue hai ise 2d banane ke liye 
print(a2)

[[1 2 3]
 [4 5 6]]


In [11]:
# Creating a 3d array
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


for finding a shape of array we use .shape

In [12]:
print(a2.shape)#2d ke andar 2 rows and 3 columns hai 
print(a3.shape)#2 2d arrays with 2 rows and 3 columns

(2, 3)
(2, 2, 3)


for finding a dimension we use .ndim


In [15]:
print(a2.ndim) #number of dimension find karte hai 
print(a3.ndim)

2
3


.dtype is used to find a innerdatype of array

In [16]:
print(a2.dtype) #array ke andar ke element ke dataype ko batata hai .dtype 

int64


numpy me range dene ke liye ham .arange ka use karte hai 

In [20]:
np.arange(11) #arange method ke through hame 1d array mil jata hai 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [21]:
np.random.randint(1,11, size =(3,3))

array([[ 1,  8,  1],
       [ 2, 10,  7],
       [ 7, 10,  8]], dtype=int32)